### PR TITLE
Migrate MLP from gojek to caraml-dev organisation

### PR DESCRIPTION
**Pull request by terryyylim**
**What this PR does / why we need it**:

This PR migrates the MLP repository from the [gojek organisation](https://github.com/gojek) (`gojek/mlp`) to the new [CaraML organisation](https://github.com/caraml-dev) (`caraml-dev/mlp`). We need to update certain dependencies that were pointing to the original repo (e.g. Docker image repositories, Go dependencies pointing to `gojek/mlp`, etc.), and also the Go module paths from `github.com/gojek/mlp` to `github.com/caraml-dev/mlp` to reflect the new changes.

Subsequently, `github.com/caraml-dev/merlin` and `github.com/caraml-dev/turing` would need to be updated as well to reference this repository.

**Which issue(s) this PR fixes**:

N/A

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by maniteja6799** [comment]
Also, update the [image repository](https://github.com/caraml-dev/helm-charts/blob/main/charts/mlp/values.yaml#L8) in the helm-chart as well?

**Review by deadlycoconuts — APPROVED** [review]
LGTM! 🚀 Thanks for the changes!

**Comment by terryyylim** [comment]
> Also, update the [image repository](https://github.com/caraml-dev/helm-charts/blob/main/charts/mlp/values.yaml#L8) in the helm-chart as well?

Yes will do once this is merged!

**Review by ariefrahmansyah — APPROVED** [review]
lgtm. thanks, @terryyylim

**Pull request merged**
